name: CI/CD Docker Build

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 
    - name: Build and push Docker image 
      run: /
        docker build --platform linux/arm64 -t my-local-app:latest .
        echo "Image my-local-app:latest built successfully locally."
