apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }} 
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: myapp-container
          image: "{{ required "image.repository is required" .Values.image.repository }}:{{ default "latest" .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
