name: Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: production  

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on server
        env:
          SSH_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_USER: ${{ secrets.DEPLOY_USER }}
          SSH_PORT: ${{ secrets.DEPLOY_PORT }}
        run: |
          PORT="${SSH_PORT:-22}"
          ssh -p "$PORT" -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" << 'EOF'
            cd /home/deploy/web
            git pull --ff-only origin main || true
            docker rm -f myapp 2>/dev/null || true
            docker run -d --restart unless-stopped --name myapp \
              -p 5003:5003 \
              -v /home/deploy/web:/app/myapp
          EOF
