name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push Docker image"]
    types: [completed]

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: production  

    steps:
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on server
        env:
          SSH_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_USER: ${{ secrets.DEPLOY_USER }}
          SSH_PORT: ${{ secrets.DEPLOY_PORT }}
        run: |
          PORT="${SSH_PORT:-22}"
          SHA="${{ github.event.workflow_run.head_sha }}"
          IMAGE="ghcr.io/andrey-gubs/myapp:sha-${SHA}"

          ssh -p "$PORT" -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" << EOF

            docker pull "$IMAGE"
            docker rm -f myapp 2>/dev/null || true
            docker run -d --restart unless-stopped --name myapp \
              -p 5003:5003 "$IMAGE"
          EOF
