name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts (auto)
        run: |
          HOST="${{ secrets.DEPLOY_HOST }}"
          PORT="${{ secrets.DEPLOY_PORT }}"
          [ -z "$PORT" ] && PORT=22
          install -m 700 -d ~/.ssh
          ssh-keyscan -H -p "$PORT" -t ed25519,ecdsa,rsa "$HOST" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: Deploy on server
        if: github.event_name == 'push'
        env:
          SSH_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_USER: ${{ secrets.DEPLOY_USER }}
          SSH_PORT: ${{ secrets.DEPLOY_PORT || 22 }}
        run: |
          PORT="${SSH_PORT:-22}"
          ssh -p "$PORT" -o StrictHostKeyChecking=yes "$SSH_USER@$SSH_HOST" << 'EOF'
            set -euo pipefail
            cd /home/deploy/web
            git pull --ff-only origin main || true
            docker build --pull -t myapp:latest .
            docker rm -f myapp 2>/dev/null || true
            docker run -d --restart unless-stopped --name myapp -p 5003:5003 myapp:latest
          EOF

