name: CI/CD Docker Build

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v3 
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/myweb:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/myweb:latest
