name: CI/CD Docker Build

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest # Запуск на последней версии Ubuntu

    steps:
    - uses: actions/checkout@v4 # Выгрузка вашего кода из репозитория
    - name: Build and push Docker image (build locally for now)
      run: docker build -t my-local-app:latest .
