name: CI/CD Docker Build

on:
  push:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.ip
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker
      run: docker build -t ghcr.io/${{ github.repository_owner }}/myweb:latest .
      
    - name: Push Docker
      run: docker push ghcr.io/${{ github.repository_owner }}/myweb:latest
